[toolchain]
channel = "nightly-2026-05-30"
targets = ["wasm32-unknown-unknown"]
components = [
    "cargo",
    "clippy",
    "rust-analyzer",
    "rust-docs",
    "rust-std",
    "rustc",
    "rustc-codegen-cranelift-preview",
]
