[package]
name = "f6-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true, features = ["macros"] }
clap = { workspace = true, features = ["derive"] }
color-eyre = { workspace = true, features = ["capture-spantrace"] }
f6-types.workspace = true
hickory-resolver.workspace = true
icann-rdap-client.workspace = true
icann-rdap-common.workspace = true
itertools = "0.14.0"
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tempfile = "3.27.0"
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal", "fs"] }
tokio-util.workspace = true
tower-http = { workspace = true, features = ["cors"] }
tracing.workspace = true
tracing-error.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[lints]
workspace = true
